version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME: IMAGE-PROCESS
      RESULT_SUFFIX: _result
      ARRAY_SUFFIX: _array
      ACCESS_TOKEN: TOKEN_FOR_DIRECT_UPLOAD
      UPLOAD_PATH: ./files
    restart: unless-stopped
    depends_on:
      - rabbitmq
